### ISSUE TITLE
Follow-up list sometimes throwing an error on demo server

### ISSUE THREAD

**Issue by mixmixmix** [CST-technology/cstweb#11]
![IXOTnDp](https://user-images.githubusercontent.com/9990867/103267556-f1e64e80-49db-11eb-85bf-15c70a955d2e.png)

**Comment by mixmixmix** [comment]
It is possibly fixed by setting a DB parameter 
```
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```
(https://github.com/CST-technology/cstweb/commit/c99d5971dee087a6cb59898f4e78907ba60b6b46)
Could you confirm @ShahnewazSarker ?

**Comment by ShahnewazSarker** [comment]
Yes, It's the solution. @mixmixmix
