### ISSUE TITLE
Dev Server - Wissel SQL Mode error

### ISSUE THREAD

**Issue by ShahnewazSarker** [CST-technology/cstweb#17]
[A Database Error Occurred
Error Number: 1055

Expression #58 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'covid_development_db.g1.name_en' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT t1.*, t2.name AS cst_name, t2.phone AS cst_phone, g1.name_en AS division, g2.name_en AS district , g3.name_en AS city_corporation, g4.name_en AS cc_ward FROM covid_case_investigation t1 LEFT JOIN covid_cst t2 ON t2.id = t1.visit_by LEFT JOIN geo_registry g1 ON g1.bbs_code = t1.division_bbs_code and g1.geo_registry_type_code = 1 LEFT JOIN geo_registry g2 ON g2.bbs_code = t1.district_bbs_code AND g2.geo_registry_type_code = 2 LEFT JOIN geo_registry g3 ON g3.bbs_code = t1.city_corporation_bbs_code AND g3.geo_registry_type_code = 3 LEFT JOIN geo_registry g4 ON g4.bbs_code = t1.cc_ward_bbs_code AND g4.geo_registry_type_code = 6 WHERE t1.visit_by IN (select id from covid_cst where am_id = '2') AND ((DATE(t1.`_1st_followup_date`)>= '2021-01-11' AND DATE(t1.`_1st_followup_date`) <= '2021-01-11') OR (DATE(t1.`_2nd_followup_date`)>= '2021-01-11' AND DATE(t1.`_2nd_followup_date`) <= '2021-01-11')) GROUP BY t1.id

Filename: models/ReportModel.php

Line Number: 110](url)

**Comment by mixmixmix** [comment]
Fixed now and is corrected for new deployments.
